### ISSUE TITLE
Use asyncio in flterm instead of threads

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/misoc#12]
If removing the C version, clean up the python version (e.g. no threads).

**Comment by enjoy-digital** [comment]
OK, I'll look at that, you suggest asyncio to remove threads?

**Comment by sbourdeauducq** [comment]
Yes, though asyncio won't work easily with pyserial yet.

**Comment by sbourdeauducq** [comment]
Done in new branch. We are keeping only the Python version, when asyncserial works we should get rid of the threads.

**Comment by sbourdeauducq** [comment]
asyncio flterm is in separate branch. Works on Linux, needs testing on Windows.

**Comment by enjoy-digital** [comment]
Just tested flterm on windows, it seems to freeze here:

https://github.com/m-labs/misoc/blob/asyncserial/misoc/tools/flterm.py#L201
https://github.com/m-labs/pyserial/blob/master/serial/aio.py#L121
https://github.com/python/asyncio/blob/master/asyncio/windows_events.py#L425
https://github.com/python/asyncio/blob/master/asyncio/windows_events.py#L605

**Comment by sbourdeauducq** [comment]
Works now.
