### ISSUE TITLE
flterm broken when run under SSH

### ISSUE THREAD

**Issue by whitequark** [m-labs/misoc#28]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/whitequark/miniconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/whitequark/miniconda/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "flterm.py", line 242, in writer
    b = getkey()
  File "flterm.py", line 19, in getkey
    old = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by sbourdeauducq** [comment]
Works fine here. Are you sure the culprit isn't e.g. tmux or mosh?

**Comment by whitequark** [comment]
Sorry, was unclear. By "under SSH" I meant like `ssh flterm ...`.

**Comment by sbourdeauducq** [comment]
Does ssh have a good reason for disallowing termios calls on the pty (or pipe?) it gives to the command you run? If you don't do those termios calls, the behavior becomes funny (double echo, characters only sent after you press ENTER).

Does ``ssh -t`` help?

**Comment by whitequark** [comment]
Yes, `ssh -t` helps. I guess this is a solution.

**Comment by mithro** [comment]
flterm should probably detect the lack of pty and throw a more useful error?
