### ISSUE TITLE
improve packet delineation in streams

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/misoc#31]
https://ssl.serverraum.org/lists-archive/devel/2016-January/004173.html
Required to fix the analyzer "data stuck" problem on ARTIQ, unless we drop dataflow completely.

**Comment by enjoy-digital** [comment]
I'm closing this since this should be fine now:
- SOP has been removed.
- EOP is still asserted with valid data (to keep things similar to AXI-stream).

**Comment by sbourdeauducq** [comment]
Thanks :+1:
