### ISSUE TITLE
asyncserial dependency not documented

### ISSUE THREAD

**Issue by jboulder** [m-labs/misoc#37]
See comment on commit  https://github.com/m-labs/misoc/commit/9f74894882b6cafa30bf5b2a2dcb09d8b2a5c07b

**Comment by jordens** [comment]
https://github.com/m-labs/asyncserial/issues/1

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/misoc/commit/a0d75a0fcecc50e170ca63aaa4314acdad8613b7
