### ISSUE TITLE
liteeth: safe detection of oversized frames

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/misoc#39]
https://github.com/m-labs/misoc/commit/e136030b0cc127af494ffc1e67da7522a4c5c57f#commitcomment-17331821

**Comment by sbourdeauducq** [comment]
@enjoy-digital ping

**Comment by enjoy-digital** [comment]
sorry, I'll look at that tomorrow morning.

**Comment by enjoy-digital** [comment]
Fixed via https://github.com/m-labs/misoc/commit/72556a6e207dec7faf42588f457344cdeb79261b.
