### ISSUE TITLE
Record.connect return value not used

### ISSUE THREAD

**Issue by tpwrules** [m-labs/misoc#80]
https://github.com/m-labs/misoc/blob/2436a68dcb24ef6624a6c9f86bdccb2f2632c158/misoc/interconnect/wishbone.py#L455-L456

I was browsing the source and it looks like the above line is a bug. The return value of `master.connect(slave)` is discarded so the connection doesn't happen. I imagine it was intended to be `self.comb += master.connect(slave)`, like in all the other places that function is used.

**Comment by jordens** [comment]
Thanks. Looks correct. Wanna shoot a patch?

**Comment by tpwrules** [comment]
Oh, I saw the contribution guidelines and it says you guys don't use pull requests. I didn't want to go through the hassle of submitting a patch on the mailing list. Feel free to make this change yourself.

**Comment by whitequark** [comment]
We do accept pull request in misoc, the contribution guide is outdated.
